add_to_list:
  description: Adds the given amount of the given product to the shopping list
  fields:
    entity_id:
      description: Product entity id(s)
      example: "sensor.product100"
    amount:
      description: Amount of product to add
      example: 1
    shopping_list:
      description: Shopping list id
      example: 1

subtract_from_list:
  description: Subtract the given amount of the given product from the shopping list
  fields:
    entity_id:
      description: Product entity id(s)
      example: "sensor.product100"
    amount:
      description: Amount of product to remove
      example: 1
    shopping_list:
      description: Shopping list id
      example: 1

add_product:
  description: Add new product to grocy
  fields:
    barcode:
      description: Product barcode (EAN-13)
      example: 7290002692478
    product_description:
      description: Product description
      example: Olive oil
    product_group_id:
      description: Product group (dairy, meat, fruits, vegetables, beverages, others)
      example: 15
    product_location_id:
      description: Product location (e.g., panatry, fridge, others)
      example: 1
    store:
      description: Store (rami levy, shufersal, mega)

remove_product:
  description: Remove product from grocy (and home assistant)
  fields:
    entity_id:
      description: Product entity id(s) or barcode sensor entity
      example: "sensor.product100"

update_product:
  description: Update product field
  fields:
    barcode:
      description: Barcode
      example: 7290008464987
    name:
      description: Product parameter name to update
      example: description
    value:
      description: Product parameter new value
      example: "This is new description"

sync:
  description: Synchronize with grocy database