add_to_list:
  description: Adds the given amount of the given product to shopping list
  fields:
    entity_id:
      description: Product entity id(s)
      example: "sensor.product100"
    amount:
      description: Amount of product to add
      example: 1
    shopping_list:
      description: Shopping list id
      example: 1

subtract_from_list:
  description: Subtract the given amount of the given product from shopping list
  fields:
    entity_id:
      description: Product entity id(s)
      example: "sensor.product100"
    amount:
      description: Amount of product to remove
      example: 1
    shopping_list:
      description: Shopping list id
      example: 1

add_product:
  description: Add / update product
  fields:
    barcode:
      description: Product barcode (EAN-13)
      example: 7290002692478
    product_description:
      description: Product description
      example: Olive oil
    product_group_id:
      description: Product group id.
      example: 15
    product_location_id:
      description: Product location id
      example: 1
    store:
      description: Online store

remove_product:
  description: Remove product
  fields:
    entity_id:
      description: Product entity id(s) or barcode sensor entity
      example: "sensor.product100"

add_favorite:
  description: Add product to favorites
  fields:
    entity_id:
      description: Product entity id(s)
      example: "sensor.product100"

remove_favorite:
  description: Remove product from favorites
  fields:
    entity_id:
      description: Product entity id(s)
      example: "sensor.product100"

sync:
  description: Synchronize with grocy database
